dependencyResolutionManagement{
    versionCatalogs{
        create("libs"){
            from(files("../libs.versions.toml"))
        }
    }
    repositories{
        google()
        mavenCentral()
    }
}
include("convention")